identifier: l4j649c4d24ad1ed
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: /Users/egorstepanov/Desktop/Dev/angular/first-app
distFolder: dist/first-app
outDir: /Users/egorstepanov/Desktop/Dev/angular/first-app/dist/static
handle404: ''
allowErrorCollect: false
